export { default as MainPage } from './MainPage'
export { default as ComicsPage } from './comicsPage/ComicsPage'
export { default as Page404 } from './404'
export { default as SingleCharPage } from './singleCharPage/SingleCharPage'
export { default as SingleComicPage } from './singleComicPage/SingleComicPage'
export * from './singleComicPage/singleComicPage.interface'
